ota/tools: Check if verify list is null
File "./gen_ota_zip.py", line 288, in gen_progress_list
  progress_list[-1] = end
IndexError: list assignment index out of range

Signed-off-by: wangjianyu3 <wangjianyu3@xiaomi.com>